version: 2.1
docker: 
 - image: cimg/node:17.5.0
orbs:
  node: circleci/node@5.0.0
  puppeteer: threetreeslight/puppeteer@0.1.2
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build-and-test:
    executor:
      name: node/default
    steps: 
      - setup_remote_docker
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: Run Tests
          command: | 
            google-chrome --version
            chromedriver --version
            export APPLITOOLS_BATCH_ID=`echo $CIRCLE_SHA1`
            echo $APPLITOOLS_BATCH_ID
            echo $APPLITOOLS_API_KEY
            echo "Installing deps"
            npm install
            echo "building static storybook"
            npx build-storybook
            docker build -t app:$APPLITOOLS_BATCH_ID .
            docker run -dp 8080:8080 app:$APPLITOOLS_BATCH_ID 
            npx eyes-storybook -u http://172.17.0.2:8080
  build-and-test-2:
    executor:
      name: node/default
    steps: 
      - setup_remote_docker
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: Run Tests
          command: | 
            google-chrome --version
            chromedriver --version
            export APPLITOOLS_BATCH_ID=`echo $CIRCLE_SHA1`
            echo $APPLITOOLS_BATCH_ID
            echo $APPLITOOLS_API_KEY
            echo "Installing deps"
            npm install
            echo "building static storybook"
            npx build-storybook
            docker build -t app$APPLITOOLS_BATCH_ID .
            docker run -dp 8080:8080 --name app$APPLITOOLS_BATCH_ID  app$APPLITOOLS_BATCH_ID 
            docker exec app$APPLITOOLS_BATCH_ID curl --retry 10 --retry-connrefused http://localhost:8080
            npx eyes-storybook -u http://172.17.0.2:8080
workflows:
    build-and-test:
      jobs:
        - build-and-test-2